AWSTemplateFormatVersion: '2010-09-09'
Description: 'Mi primera plantilla de infraestructura como código con EC2, S3 y Apache'

Parameters:
  BucketName:
    Type: String
    Description: Nombre del bucket S3
    Default: bucket-sm-g002

  InstanceName:
    Type: String
    Description: Nombre para la instancia EC2
    Default: sara-garcia1

Resources:
  BucketS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  
  
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "*"
            
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Permitir trafico HTTP'  # Se ha eliminado el acento en "tráfico"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Permite acceso HTTP desde cualquier lugar

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e449927258d45bc4  # Amazon Linux 2 en us-east-1 (verifica si estás en otra región)
      SecurityGroupIds:
        - !Ref EC2SecurityGroup  # Usamos el grupo de seguridad directamente
      IamInstanceProfile: !Ref EC2InstanceProfile
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          aws s3 cp s3://${BucketName}/index.html /var/www/html/index.html
      Tags:
        - Key: Name
          Value: !Ref InstanceName

Outputs:
  NombreDelBucket:
    Description: Nombre del bucket S3 creado
    Value: !Ref BucketS3
    Export:
      Name: NombreExportadoBucketS3

  ARNBucket:
    Description: ARN del bucket S3
    Value: !GetAtt BucketS3.Arn
    Export:
      Name: ArnExportadoBucketS3

  NombreDeInstancia:
    Description: Nombre asignado a la instancia EC2
    Value: !Ref InstanceName
    Export:
      Name: NombreExportadoEC2

  EC2PublicIP:
    Description: IP publica de la instancia EC2
    Value: !GetAtt EC2Instance.PublicIp  # Esto debería funcionar con subred pública
